// GENERATED BY MITOSIS

import Checkbox from "../checkbox/checkbox";
import {
  Fragment,
  component$,
  h,
  useClientEffect$,
  useStore,
} from "@builder.io/qwik";
export interface ChecklistProps {
  theme?: string;
  label?: string;
}
export const Checklist = component$((props: ChecklistProps) => {
  const state = useStore<any>({ theme: `blue` });
  useClientEffect$(() => {
    state.theme = props.theme || `blue`;
  });
  return <Checkbox label={props.label}></Checkbox>;
});
export default Checklist;
