// GENERATED BY MITOSIS

import Item from "../item/item";
import {
  Fragment,
  Slot,
  component$,
  h,
  useClientEffect$,
} from "@builder.io/qwik";
export interface CheckboxProps {
  label?: string;
  children?: any;
}
export const Checkbox = component$((props: CheckboxProps) => {
  useClientEffect$(() => {});
  return (
    <Item>
      <input type="checkbox"></input>
      <label>{props.label}</label>
      <Slot></Slot>
    </Item>
  );
});
export default Checkbox;
