// GENERATED BY MITOSIS

import {
  Fragment,
  Slot,
  component$,
  h,
  useClientEffect$,
  useStore,
} from "@builder.io/qwik";
export const Button = component$((props) => {
  const state = useStore({ 
    color: "#ffffff", 
    fill: "solid", 
    radius: "md" });
  useClientEffect$(() => {
    state.color = props.color || "#ffffff";
    state.fill = props.fill || "solid";
    state.radius = props.radius || "md";
  });
  return (
    <div
      style={{
        fontFamily: "inherit",
        fontSize:
          (props.size === "large" && "2rem") ||
          (props.size === "small" && "1.1rem") ||
          "1.2rem",
        textDecoration: "none",
        color: "inherit",
        display: "inline-flex",
        gap: "8px",
        alignItems: "center",
        // border:
        //   state.fill === "outline"
        //     ? `1px solid ${
        //         state.color
        //           ? ((state.color.includes("#") || state.color.includes("(")) &&
        //               state.color) ||
        //             `var(--color-${state.color})`
        //           : "#ffffff"
        //       }`
        //     : "none",
        // background: state.color
        //   ? ((state.color.includes("#") || state.color.includes("(")) &&
        //       state.color) ||
        //     `var(--color-${state.color})`
        //   : "#ffffff",
        // padding:
        //   (props.size === "large" && "var(--size-2) var(--size-5)") ||
        //   (props.size === "small" && "var(--size-px) var(--size-2)") ||
        //   "var(--size-1) var(--size-4)",
        // borderRadius:
        //   (state.radius === "none" && "none") ||
        //   `var(--radius-${state.radius || ""})`,
        // boxShadow:
        //   (state.fill !== "solid" && "none") ||
        //   (props.size === "large" && "var(--shadow-md)") ||
        //   (props.size === "small" && "var(--shadow-xs)") ||
        //   "var(--shadow-sm)",
      }}
    >
      <Slot></Slot>
    </div>
  );
});
export default Button;
