// GENERATED BY MITOSIS

import Button from "../button/button";
import {
  Fragment,
  Slot,
  component$,
  h,
  useCleanup$,
  useClientEffect$,
  useRef,
  useStore,
} from "@builder.io/qwik";
export const onInput = function onInput(props, state, formRef, event) {
  void (async function () {
    const saveCache = async function () {
      localStorage.setItem(props?.cacheKey, JSON.stringify(props?.formData));
    };
    const setFilteredValue = async function (key, value) {
      let newValue = value;
      const filters =
        (typeof props?.filterData === "string"
          ? props?.filterData?.split?.(",")
          : props?.filterData) || [];
      for (const filter of filters) {
        if (typeof filter !== "function") continue;
        const filterName =
          Object.getOwnPropertyDescriptors(filter)?.name?.value;
        if (!filterName || filterName !== key) continue;
        newValue = await filter(value);
      }
      return newValue;
    };
    const setByPath = function (obj, path, value) {
      const pList = path.split(".");
      const len = pList.length;
      for (let i = 0; i < len - 1; i++) {
        const nextElemIsArray = !isNaN(parseInt(pList[i + 1]));
        const elem = pList[i];
        if (!obj[elem]) obj[elem] = nextElemIsArray ? [] : {};
        obj = obj[elem];
      }
      obj[pList[len - 1]] = value;
      return obj;
    };
    if (
      event?.target?.name?.length &&
      !event?.target?.name?.startsWith?.("ion-")
    ) {
      const value =
        typeof event?.detail?.checked === "boolean"
          ? event.detail.checked
          : event?.detail?.value || event?.target?.value;
      setByPath(
        state?.formData || {},
        event?.target?.name,
        props?.filterData?.length
          ? await setFilteredValue(event?.target?.name, value)
          : value
      );
      if (props.cacheKey) await saveCache();
      if (!state?.hasChanged) {
        state.hasChanged = true;
      }
    }
  })();
};
export const submit = function submit(props, state, formRef, event) {
  (event?.target || document).dispatchEvent(
    new CustomEvent("fireenjinSubmit", {
      bubbles: true,
      detail: {
        event,
        endpoint: props?.action,
        data: state?.formData || null,
      },
    })
  );
};
export const Form = component$((props: any) => {
  const formRef = useRef();
  const state = useStore<any>({
    eventListeners: [
      "ionInput",
      "ionChange",
      "ionSelect",
      "input",
      "change",
      "fireenjinCodeChange",
    ],
    formData: {},
    hasChanged: false,
    resetButton: "Clear",
    resetButtonFill: "solid",
    resetButtonRadius: "md",
    resetButtonTheme: "grey",
    submitButton: "Save",
    submitButtonFill: "solid",
    submitButtonRadius: "md",
    submitButtonTheme: "blue",
  });
  useClientEffect$(() => {
    if (props.formData) state.formData = props.formData;
    if (props.eventListeners) state.eventListeners = props.eventListeners;
    state.submitButton = props?.submitButton ?? "Save";
    state.submitButtonTheme = props?.submitButtonTheme || "blue";
    state.submitButtonFill = props?.submitButtonFill || "solid";
    state.submitButtonRadius = props?.submitButtonRadius || "md";
    state.resetButton = props?.resetButton ?? "Clear";
    state.resetButtonTheme = props?.resetButtonTheme || "grey";
    state.resetButtonFill = props?.resetButtonFill || "solid";
    state.resetButtonRadius = props?.submitButtonRadius || "md";
    const ref = formRef?.current;
    if (ref?.addEventListener)
      state.eventListeners.map((eventName) =>
        ref.addEventListener(
          eventName,
          onInput.bind(null, props, state, formRef).bind(this)
        )
      );
  });
  useCleanup$(() => {
    const ref = formRef?.current;
    if (ref) {
      (props?.eventListeners || []).map((eventName) =>
        ref.removeEventListener(
          eventName,
          onInput.bind(null, props, state, formRef).bind(this)
        )
      );
    }
  });
  return (
    <form
      preventdefault:submit=""
      ref={formRef}
      onSubmit$={(event) => {
        event.preventDefault();
        submit(props, state, formRef, event);
      }}
      action={props?.action}
      method={props?.method}
    >
      <Slot></Slot>
      {!props.hideControls ? (
        <div
          class="form-controls"
          style={{
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          {state.resetButton ? (
            <Button
              type="reset"
              theme={state.resetButtonTheme}
              fill={state.resetButtonFill}
              radius={state.resetButtonRadius}
            >
              {state.resetButton}
            </Button>
          ) : null}
          {state.submitButton ? (
            <Button
              type="submit"
              theme={state.submitButtonTheme}
              fill={state.submitButtonFill}
              radius={state.submitButtonRadius}
            >
              {state.submitButton}
            </Button>
          ) : null}
        </div>
      ) : null}
    </form>
  );
});
export default Form;
