import { componentQrl, inlinedQrl, useStylesScopedQrl, Slot } from '@builder.io/qwik';
import { jsx } from '@builder.io/qwik/jsx-runtime';

const pollen = '';

const global = '';

// GENERATED BY MITOSIS
const Button = /*#__PURE__*/ componentQrl(inlinedQrl((props)=>{
    useStylesScopedQrl(inlinedQrl(STYLES, "Button_component_useStylesScoped_ADIyYeY0NdY"));
    return /*#__PURE__*/ jsx("a", {
        type: "button",
        class: "a-Button",
        href: props?.href,
        style: {
            background: `var(--color-${props?.color})`
        },
        children: /*#__PURE__*/ jsx(Slot, {})
    });
}, "Button_component_0c0eZeZK1vk"));
const STYLES = `.a-Button { 
text-decoration: none;
font-weight: bold;
color: white;
padding: 15px; }`;

// GENERATED BY MITOSIS
const Form = /*#__PURE__*/ componentQrl(inlinedQrl((props)=>{
    return /*#__PURE__*/ jsx("form", {
        action: props?.action,
        method: props?.method,
        children: /*#__PURE__*/ jsx(Slot, {})
    });
}, "Form_component_xe7wWdy1GII"));

export { Button, Form };
