'use strict';

Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: 'Module' } });

const qwik = require('@builder.io/qwik');
const jsxRuntime = require('@builder.io/qwik/jsx-runtime');

const pollen = '';

const global = '';

// GENERATED BY MITOSIS
const Button = /*#__PURE__*/ qwik.componentQrl(qwik.inlinedQrl((props)=>{
    qwik.useStylesScopedQrl(qwik.inlinedQrl(STYLES, "Button_component_useStylesScoped_ADIyYeY0NdY"));
    return /*#__PURE__*/ jsxRuntime.jsx("a", {
        type: "button",
        class: "a-Button",
        href: props?.href,
        style: {
            background: `var(--color-${props?.color})`
        },
        children: /*#__PURE__*/ jsxRuntime.jsx(qwik.Slot, {})
    });
}, "Button_component_0c0eZeZK1vk"));
const STYLES = `.a-Button { 
text-decoration: none;
font-weight: bold;
color: white;
padding: 15px; }`;

// GENERATED BY MITOSIS
const Form = /*#__PURE__*/ qwik.componentQrl(qwik.inlinedQrl((props)=>{
    return /*#__PURE__*/ jsxRuntime.jsx("form", {
        action: props?.action,
        method: props?.method,
        children: /*#__PURE__*/ jsxRuntime.jsx(qwik.Slot, {})
    });
}, "Form_component_xe7wWdy1GII"));

exports.Button = Button;
exports.Form = Form;
