// GENERATED BY MITOSIS

import {
  Fragment,
  Slot,
  component$,
  h,
  useClientEffect$,
} from "@builder.io/qwik";
export interface ItemProps {
  children?: any;
}
export const Item = component$((props: ItemProps) => {
  useClientEffect$(() => {});
  return (
    <li class="item-wrapper">
      <Slot></Slot>
    </li>
  );
});
export default Item;
