// GENERATED BY MITOSIS

import {
  Fragment,
  Slot,
  component$,
  h,
  useStylesScoped$,
} from "@builder.io/qwik";
export const Button = component$((props) => {
  useStylesScoped$(STYLES);
  return (
    <a
      type="button"
      class="a-Button"
      href={props?.href}
      style={{
        background: `var(--color-${props?.color})`,
      }}
    >
      <Slot></Slot>
    </a>
  );
});
export default Button;
export const STYLES = `
.a-Button {
  text-decoration: none;
  font-weight: bold;
  color: white;
  padding: 15px;
}`;
