import { Color, SelectCompareFn, SelectInterface } from "@ionic/core";

export type FieldOption = {
  label?: string;
  value?: any;
  checked?: boolean;
  disabled?: boolean;
  payload?: any;
  slot?: string;
  color?: Color;
};

export type Control = {
  name: string;
  icon?: string;
  label?: string;
  value?: any;
  header?: string;
  subHeader?: string;
  message?: string;
  optionEl?: (result: any) => any;
  endpoint?: string;
  query?: string;
  limit?: number;
  orderBy?: string;
  dataPropsMap?: any;
  params?: any;
  multiple?: boolean;
  disabled?: boolean;
  cancelText?: string;
  okText?: string;
  placeholder?: string;
  selectedText?: string;
  interface?: SelectInterface;
  interfaceOptions?: any;
  compareWith?: string | SelectCompareFn | null;
  options?: FieldOption[];
};

export type Field = {
  compareWith?: string | SelectCompareFn | null;
  options?: FieldOption[];
  beforeHTML?: string;
  innerHTML?: string;
  afterHTML?: string;
  path?: string;
  fileName?: string;
  accept?: string;
  defaultValue?: any;
  documentId?: string;
  stripeKey?: string;
  type?: any;
  required?: any;
  autocomplete?: "on" | "off";
  autocapitalize?: string;
  autocorrect?: "on" | "off";
  autofocus?: boolean;
  googleMapsKey?: string;
  minlength?: number;
  maxlength?: number;
  info?: string;
  edit?: boolean;
  min?: string;
  max?: string;
  iconLeft?: string;
  iconRight?: string;
  silence?: boolean;
  step?: string;
  actionOptions?: any;
  pattern?: any;
  clearInput?: boolean;
  readOnly?: boolean;
  spellCheck?: boolean;
  inputMode?: string;
  stripeElements?: any;
  lines?: "full" | "inset" | "none";
  labelPosition?: "stacked" | "fixed" | "floating";
  resultsKey?: string;
  name?: string;
  icon?: string;
  label?: string;
  value?: any;
  header?: string;
  subHeader?: string;
  fallback?: string;
  message?: string;
  optionEl?: (result: any) => any;
  endpoint?: string;
  query?: string;
  limit?: number;
  orderBy?: string;
  dataPropsMap?: any;
  params?: any;
  multiple?: boolean;
  disabled?: boolean;
  cancelText?: string;
  okText?: string;
  placeholder?: string;
  selectedText?: string;
  interface?: SelectInterface;
  interfaceOptions?: any;
  uploadData?: any;
  showButton?: boolean;
  buttonText?: string;
  initials?: string;
  resize?: boolean;
  loading?: boolean;
  template?: (result) => any;
  searchParams?: any;
  mode?: string;
  results?: any;
};

export type Step = {
  beforeHTML?: string;
  name?: string;
  fields?: Field[];
  innerHTML?: string;
  afterHTML?: string;
  component?: string;
  componentProps?: any;
};

export type FilterControl = {
  resultsKey?: string;
  name: string;
  icon?: string;
  label?: string;
  value?: any;
  header?: string;
  subHeader?: string;
  message?: string;
  optionEl?: (result: any) => any;
  endpoint?: string;
  query?: string;
  limit?: number;
  orderBy?: string;
  dataPropsMap?: any;
  params?: any;
  multiple?: boolean;
  disabled?: boolean;
  cancelText?: string;
  okText?: string;
  placeholder?: string;
  selectedText?: string;
  interface?: SelectInterface;
  interfaceOptions?: any;
  compareWith?: string | SelectCompareFn | null;
  options?: FieldOption[];
};
