// GENERATED BY MITOSIS

import { Fragment, Slot, component$, h } from "@builder.io/qwik";
export interface ListProps {
  ordered?: boolean;
  listType?: string;
  children?: any;
}
export const List = component$((props: ListProps) => {
  return (
    <span>
      {props.ordered ? (
        <ol
          style={{
            "list-style-type": `${props.listType ? props.listType : "decimal"}`,
          }}
        >
          <Slot></Slot>
        </ol>
      ) : null}
      {!props.ordered ? (
        <ul
          style={{
            "list-style-type": `${props.listType ? props.listType : "none"}`,
          }}
        >
          <Slot></Slot>
        </ul>
      ) : null}
    </span>
  );
});
export default List;
