name: Release
on:
  push:
    branches:
      - v2
jobs:
  release-qwik:
    name: Release Qwik
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Install Qwik Dependencies
        working-directory: ./packages/qwik
        run: npm install
      - name: Build Qwik
        run: npm run build:qwik
      - name: Release Qwik
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/qwik
        run: npx semantic-release
      - run: echo -e "@fireenjin:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Release Github Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/qwik
        run: npm publish
